[110,125,130,146,157,178,189,199,210]

Data preprocessing


X                             Y

t1   t2   t3

110 125 130                  146

189  199 210                  ?




In [1]:

# univariate lstm example
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten

In [3]:
# preparing independent and dependent features
def prepare_data(timeseries_data, n_features):
    X, y =[],[]
    for i in range(len(timeseries_data)):
        # find the end of this pattern
        end_ix = i + n_features
        # check if we are beyond the sequence
        if end_ix > len(timeseries_data)-1:
            break
        # gather input and output parts of the pattern
        seq_x, seq_y = timeseries_data[i:end_ix], timeseries_data[end_ix]
        X.append(seq_x)
        y.append(seq_y)
    return np.array(X), np.array(y)

In [4]:

# define input sequence
timeseries_data = [110,125,130,146,157,178,189,199,210]
# choose a number of time steps
n_steps = 3
# split into samples
X, y = prepare_data(timeseries_data, n_steps)

In [5]:

print(X),print(y)

[[110 125 130]
 [125 130 146]
 [130 146 157]
 [146 157 178]
 [157 178 189]
 [178 189 199]]
[146 157 178 189 199 210]


(None, None)

In [6]:
X.shape

(6, 3)

In [7]:
# reshape from [samples, timesteps] into [samples, timesteps, features]
n_features = 1
X = X.reshape((X.shape[0], X.shape[1], n_features))

# Building LSTM Model

In [8]:

# define model
model = Sequential()
model.add(LSTM(50, activation='relu', return_sequences=True, input_shape=(n_steps, n_features)))
model.add(LSTM(50, activation='relu'))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')
# fit model
model.fit(X, y, epochs=300, verbose=1)

Epoch 1/300
1/1 [==============================] - 0s 2ms/step - loss: 32715.5098
Epoch 2/300
1/1 [==============================] - 0s 5ms/step - loss: 32173.7480
Epoch 3/300
1/1 [==============================] - 0s 2ms/step - loss: 31684.1816
Epoch 4/300
1/1 [==============================] - 0s 3ms/step - loss: 31217.9121
Epoch 5/300
1/1 [==============================] - 0s 2ms/step - loss: 30767.9160
Epoch 6/300
1/1 [==============================] - 0s 2ms/step - loss: 30341.5312
Epoch 7/300
1/1 [==============================] - 0s 2ms/step - loss: 29932.5449
Epoch 8/300
1/1 [==============================] - 0s 4ms/step - loss: 29540.1328
Epoch 9/300
1/1 [==============================] - 0s 2ms/step - loss: 29163.4941
Epoch 10/300
1/1 [==============================] - 0s 3ms/step - loss: 28800.6719
Epoch 11/300
1/1 [==============================] - 0s 2ms/step - loss: 28445.1230
Epoch 12/300
1/1 [==============================] - 0s 3ms/step - loss: 28086.8438
Epoch 13/300


1/1 [==============================] - 0s 2ms/step - loss: 49.1673
Epoch 102/300
1/1 [==============================] - 0s 998us/step - loss: 48.9940
Epoch 103/300
1/1 [==============================] - 0s 998us/step - loss: 48.8007
Epoch 104/300
1/1 [==============================] - 0s 2ms/step - loss: 48.6328
Epoch 105/300
1/1 [==============================] - 0s 997us/step - loss: 48.4856
Epoch 106/300
1/1 [==============================] - 0s 2ms/step - loss: 48.2661
Epoch 107/300
1/1 [==============================] - 0s 2ms/step - loss: 47.9762
Epoch 108/300
1/1 [==============================] - 0s 2ms/step - loss: 47.6723
Epoch 109/300
1/1 [==============================] - 0s 3ms/step - loss: 47.2537
Epoch 110/300
1/1 [==============================] - 0s 3ms/step - loss: 46.8607
Epoch 111/300
1/1 [==============================] - 0s 2ms/step - loss: 46.5828
Epoch 112/300
1/1 [==============================] - 0s 3ms/step - loss: 46.1348
Epoch 113/300
1/1 [=================

1/1 [==============================] - 0s 2ms/step - loss: 20.4860
Epoch 202/300
1/1 [==============================] - 0s 3ms/step - loss: 20.1458
Epoch 203/300
1/1 [==============================] - 0s 997us/step - loss: 19.9518
Epoch 204/300
1/1 [==============================] - 0s 2ms/step - loss: 19.8688
Epoch 205/300
1/1 [==============================] - 0s 2ms/step - loss: 19.5654
Epoch 206/300
1/1 [==============================] - 0s 2ms/step - loss: 19.2435
Epoch 207/300
1/1 [==============================] - 0s 3ms/step - loss: 19.0333
Epoch 208/300
1/1 [==============================] - 0s 997us/step - loss: 18.7556
Epoch 209/300
1/1 [==============================] - 0s 3ms/step - loss: 18.3525
Epoch 210/300
1/1 [==============================] - 0s 996us/step - loss: 17.9802
Epoch 211/300
1/1 [==============================] - 0s 2ms/step - loss: 17.8500
Epoch 212/300
1/1 [==============================] - 0s 998us/step - loss: 17.7256
Epoch 213/300
1/1 [===============

# Predicting For the next 10 data

In [14]:
# demonstrate prediction for next 10 days
x_input = np.array([187, 196, 210])
temp_input=list(x_input)
lst_output=[]
i=0
while(i<10):
    
    if(len(temp_input)>3):
        x_input=np.array(temp_input[1:])
        print("{} day input {}".format(i,x_input))
        #print(x_input)
        x_input = x_input.reshape((1, n_steps, n_features))
        #print(x_input)
        yhat = model.predict(x_input, verbose=0)
        print("{} day output {}".format(i,yhat))
        temp_input.append(yhat[0][0])
        temp_input=temp_input[1:]
        #print(temp_input)
        lst_output.append(yhat[0][0])
        i=i+1
    else:
        x_input = x_input.reshape((1, n_steps, n_features))
        yhat = model.predict(x_input, verbose=0)
        print(yhat[0])
        temp_input.append(yhat[0][0])
        lst_output.append(yhat[0][0])
        i=i+1
    

print(lst_output)

[217.48265]
1 day input [196.         210.         217.48265076]
1 day output [[227.34439]]
2 day input [210.         217.48265076 227.34439087]
2 day output [[237.09036]]
3 day input [217.48265 227.34439 237.09036]
3 day output [[245.11507]]
4 day input [227.34439 237.09036 245.11507]
4 day output [[254.09525]]
5 day input [237.09036 245.11507 254.09525]
5 day output [[262.72003]]
6 day input [245.11507 254.09525 262.72003]
6 day output [[270.80618]]
7 day input [254.09525 262.72003 270.80618]
7 day output [[279.28745]]
8 day input [262.72003 270.80618 279.28745]
8 day output [[287.52374]]
9 day input [270.80618 279.28745 287.52374]
9 day output [[295.61273]]
[217.48265, 227.34439, 237.09036, 245.11507, 254.09525, 262.72003, 270.80618, 279.28745, 287.52374, 295.61273]


In [15]:

timeseries_data

[110, 125, 130, 146, 157, 178, 189, 199, 210]

In [16]:
lst_output

[217.48265,
 227.34439,
 237.09036,
 245.11507,
 254.09525,
 262.72003,
 270.80618,
 279.28745,
 287.52374,
 295.61273]