In [1]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:

### Vocabulary size
voc_size=10000

## one hot rep

In [6]:

onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[369, 5624, 9958, 7149], [369, 5624, 9958, 6518], [369, 1828, 9958, 395], [5512, 8052, 1377, 2164, 7986], [5512, 8052, 1377, 2164, 3051], [4444, 369, 5417, 9958, 3630], [679, 5356, 374, 2164]]


## Word Embedding Representation

In [7]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential    

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0  369 5624 9958 7149]
 [   0    0    0    0  369 5624 9958 6518]
 [   0    0    0    0  369 1828 9958  395]
 [   0    0    0 5512 8052 1377 2164 7986]
 [   0    0    0 5512 8052 1377 2164 3051]
 [   0    0    0 4444  369 5417 9958 3630]
 [   0    0    0    0  679 5356  374 2164]]


In [10]:
dim=10

In [11]:

model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [13]:
print(model.predict(embedded_docs))

[[[ 1.96757801e-02 -4.87879664e-03  2.91951001e-05 -1.52949691e-02
    3.30215953e-02  4.50507551e-03 -1.95573699e-02 -1.31250843e-02
    1.82601474e-02  4.98836897e-02]
  [ 1.96757801e-02 -4.87879664e-03  2.91951001e-05 -1.52949691e-02
    3.30215953e-02  4.50507551e-03 -1.95573699e-02 -1.31250843e-02
    1.82601474e-02  4.98836897e-02]
  [ 1.96757801e-02 -4.87879664e-03  2.91951001e-05 -1.52949691e-02
    3.30215953e-02  4.50507551e-03 -1.95573699e-02 -1.31250843e-02
    1.82601474e-02  4.98836897e-02]
  [ 1.96757801e-02 -4.87879664e-03  2.91951001e-05 -1.52949691e-02
    3.30215953e-02  4.50507551e-03 -1.95573699e-02 -1.31250843e-02
    1.82601474e-02  4.98836897e-02]
  [ 3.87689956e-02  4.46522273e-02  8.84820148e-03 -1.68893225e-02
    4.62261923e-02  2.15415023e-02 -4.66154218e-02  7.71741942e-03
   -2.01520082e-02 -1.12878792e-02]
  [-3.54468115e-02  3.11742090e-02  4.92493175e-02 -3.85834202e-02
    2.38402821e-02 -8.80815834e-03 -5.93702868e-03  3.53262685e-02
   -4.58163880e-

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0,  369, 5624, 9958, 7149])

In [15]:
print(model.predict(embedded_docs)[0])  # we get for 10 dimensions

[[ 1.9675780e-02 -4.8787966e-03  2.9195100e-05 -1.5294969e-02
   3.3021595e-02  4.5050755e-03 -1.9557370e-02 -1.3125084e-02
   1.8260147e-02  4.9883690e-02]
 [ 1.9675780e-02 -4.8787966e-03  2.9195100e-05 -1.5294969e-02
   3.3021595e-02  4.5050755e-03 -1.9557370e-02 -1.3125084e-02
   1.8260147e-02  4.9883690e-02]
 [ 1.9675780e-02 -4.8787966e-03  2.9195100e-05 -1.5294969e-02
   3.3021595e-02  4.5050755e-03 -1.9557370e-02 -1.3125084e-02
   1.8260147e-02  4.9883690e-02]
 [ 1.9675780e-02 -4.8787966e-03  2.9195100e-05 -1.5294969e-02
   3.3021595e-02  4.5050755e-03 -1.9557370e-02 -1.3125084e-02
   1.8260147e-02  4.9883690e-02]
 [ 3.8768996e-02  4.4652227e-02  8.8482015e-03 -1.6889323e-02
   4.6226192e-02  2.1541502e-02 -4.6615422e-02  7.7174194e-03
  -2.0152008e-02 -1.1287879e-02]
 [-3.5446811e-02  3.1174209e-02  4.9249317e-02 -3.8583420e-02
   2.3840282e-02 -8.8081583e-03 -5.9370287e-03  3.5326269e-02
  -4.5816388e-02 -4.8453584e-03]
 [-3.9259650e-02 -4.3545283e-02 -4.3031372e-02 -1.0162927e